name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: findy-network/setup-go-action@master
        with:
          linter-config-path: .golangci.yml
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: make test_cov_out
      - name: upload
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.txt
